name: Deploy Fintech Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.anish }}
          port: ${{ secrets.8000 }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/anish/Fintech-Credit-Card-System
            bash .scripts/deploy.sh
